//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



public sealed class AuthSettings
{

    private static AuthSettingsSection _config;

    static AuthSettings()
    {
        _config = ((AuthSettingsSection)(global::System.Configuration.ConfigurationManager.GetSection("authSettings")));
    }

    private AuthSettings()
    {
    }

    public static AuthSettingsSection Config
    {
        get
        {
            return _config;
        }
    }
}

public sealed partial class AuthSettingsSection : System.Configuration.ConfigurationSection
{

    [System.Configuration.ConfigurationPropertyAttribute("AccessTokenKey")]
    public AccessTokenKeyElement AccessTokenKey
    {
        get
        {
            return ((AccessTokenKeyElement)(this["AccessTokenKey"]));
        }
    }

    [System.Configuration.ConfigurationPropertyAttribute("externalAuth")]
    public ExternalAuthElement ExternalAuth
    {
        get
        {
            return ((ExternalAuthElement)(this["externalAuth"])) ?? new ExternalAuthElement();
        }
    }

    public sealed partial class AccessTokenKeyElement : System.Configuration.ConfigurationElement
    {

        [System.Configuration.ConfigurationPropertyAttribute("local", IsRequired = true)]
        public string Local
        {
            get
            {
                return ((string)(this["local"]));
            }
            set
            {
                this["local"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("external", IsRequired = true)]
        public string External
        {
            get
            {
                return ((string)(this["external"]));
            }
            set
            {
                this["external"] = value;
            }
        }
    }

    public sealed partial class ExternalAuthElement : System.Configuration.ConfigurationElement
    {

        [System.Configuration.ConfigurationPropertyAttribute("google")]
        public GoogleElement Google
        {
            get
            {
                return ((GoogleElement)(this["google"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("vkontakte")]
        public VkontakteElement Vkontakte
        {
            get
            {
                return ((VkontakteElement)(this["vkontakte"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("facebook")]
        public FacebookElement Facebook
        {
            get
            {
                return ((FacebookElement)(this["facebook"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("twitter")]
        public TwitterElement Twitter
        {
            get
            {
                return ((TwitterElement)(this["twitter"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("esia")]
        public EsiaElement Esia
        {
            get
            {
                return ((EsiaElement)(this["esia"]));
            }
        }

        public sealed partial class GoogleElement : System.Configuration.ConfigurationElement
        {

            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired = true)]
            public bool Enabled
            {
                get
                {
                    return ((bool)(this["enabled"]));
                }
                set
                {
                    this["enabled"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("redirectUrl", IsRequired = true)]
            public string RedirectUrl
            {
                get
                {
                    return ((string)(this["redirectUrl"]));
                }
                set
                {
                    this["redirectUrl"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("clientId", IsRequired = true)]
            public string ClientId
            {
                get
                {
                    return ((string)(this["clientId"]));
                }
                set
                {
                    this["clientId"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("clientSecret", IsRequired = true)]
            public string ClientSecret
            {
                get
                {
                    return ((string)(this["clientSecret"]));
                }
                set
                {
                    this["clientSecret"] = value;
                }
            }
        }

        public sealed partial class VkontakteElement : System.Configuration.ConfigurationElement
        {

            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired = true)]
            public bool Enabled
            {
                get
                {
                    return ((bool)(this["enabled"]));
                }
                set
                {
                    this["enabled"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("redirectUrl", IsRequired = true)]
            public string RedirectUrl
            {
                get
                {
                    return ((string)(this["redirectUrl"]));
                }
                set
                {
                    this["redirectUrl"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("appId", IsRequired = true)]
            public string AppId
            {
                get
                {
                    return ((string)(this["appId"]));
                }
                set
                {
                    this["appId"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("appSecret", IsRequired = true)]
            public string AppSecret
            {
                get
                {
                    return ((string)(this["appSecret"]));
                }
                set
                {
                    this["appSecret"] = value;
                }
            }
        }

        public sealed partial class FacebookElement : System.Configuration.ConfigurationElement
        {

            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired = true)]
            public bool Enabled
            {
                get
                {
                    return ((bool)(this["enabled"]));
                }
                set
                {
                    this["enabled"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("redirectUrl", IsRequired = true)]
            public string RedirectUrl
            {
                get
                {
                    return ((string)(this["redirectUrl"]));
                }
                set
                {
                    this["redirectUrl"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("appId", IsRequired = true)]
            public string AppId
            {
                get
                {
                    return ((string)(this["appId"]));
                }
                set
                {
                    this["appId"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("appSecret", IsRequired = true)]
            public string AppSecret
            {
                get
                {
                    return ((string)(this["appSecret"]));
                }
                set
                {
                    this["appSecret"] = value;
                }
            }
        }

        public sealed partial class TwitterElement : System.Configuration.ConfigurationElement
        {

            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired = true)]
            public bool Enabled
            {
                get
                {
                    return ((bool)(this["enabled"]));
                }
                set
                {
                    this["enabled"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("redirectUrl", IsRequired = true)]
            public string RedirectUrl
            {
                get
                {
                    return ((string)(this["redirectUrl"]));
                }
                set
                {
                    this["redirectUrl"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("consumerKey", IsRequired = true)]
            public string ConsumerKey
            {
                get
                {
                    return ((string)(this["consumerKey"]));
                }
                set
                {
                    this["consumerKey"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("consumerSecret", IsRequired = true)]
            public string ConsumerSecret
            {
                get
                {
                    return ((string)(this["consumerSecret"]));
                }
                set
                {
                    this["consumerSecret"] = value;
                }
            }
        }

        public sealed partial class EsiaElement : System.Configuration.ConfigurationElement
        {

            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired = true)]
            public bool Enabled
            {
                get
                {
                    return ((bool)(this["enabled"]));
                }
                set
                {
                    this["enabled"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("redirectUrl", IsRequired = true)]
            public string RedirectUrl
            {
                get
                {
                    return ((string)(this["redirectUrl"]));
                }
                set
                {
                    this["redirectUrl"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("Issuer", IsRequired = true)]
            public string Issuer
            {
                get
                {
                    return ((string)(this["Issuer"]));
                }
                set
                {
                    this["Issuer"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("PFXFileName", IsRequired = true)]
            public string PFXFileName
            {
                get
                {
                    return ((string)(this["PFXFileName"]));
                }
                set
                {
                    this["PFXFileName"] = value;
                }
            }

            [System.Configuration.ConfigurationPropertyAttribute("PFXPassword", IsRequired = true)]
            public string PFXPassword
            {
                get
                {
                    return ((string)(this["PFXPassword"]));
                }
                set
                {
                    this["PFXPassword"] = value;
                }
            }
        }
    }
}
