// <auto-generated />
namespace Data.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OSViewAddEUSINumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OSViewAddEUSINumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201902220707508_OSViewAddEUSINumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
