// <auto-generated />
namespace Data.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddActualityDateIH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActualityDateIH));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170948506_AddActualityDateIH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
