// <auto-generated />
namespace Data.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSP_MasterDataControlRent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSP_MasterDataControlRent));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251450176_AddSP_MasterDataControlRent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
